imports:
    - { resource: tables.yml }
services:
    dmzx.buttonindex.admin.controller:
        class: dmzx\buttonindex\controller\admin_controller
        arguments:
            - '@config'
            - '@template'
            - '@log'
            - '@user'
            - '@dbal.conn'
            - '@request'
            - '%tables.buttonindex_table%'
    dmzx.buttonindex.listener:
        class: dmzx\buttonindex\event\listener
        arguments:
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@request'
            - '%tables.buttonindex_table%'
        tags:
            - { name: event.listener }
